### PR TITLE
Drag handler moved

### PR DESCRIPTION
**Pull request by MaciejPadula**
- Dragging on device name (before whole element was draggable)
- Grab cursor only when user is room owner

### CODE REVIEW

**Review by LUKIS123 — COMMENTED** [review]
Znowu ten front :((

**Comment by LUKIS123** [comment]
ok

**Comment by MaciejPadula** [comment]
> Znowu ten front :((

Tak

**Comment by LUKIS123** [comment]
ok

**Comment by LUKIS123** [comment]
ok

**Review by LUKIS123 — APPROVED** [review]

**Pull request merged**
